@startuml GeneralStructure

skinparam{
    backgroundColor #202020
    defaultFontName Courier
    defaultFontColor #FFFFFF

    ClassBackgroundColor #333333
    ClassBorderColor #AAAAAA
    ClassHeaderBackgroundColor #444444
    ClassFontSize 19
    ClassFontStyle bold
    ClassAttributeFontSize 17


    Linetype ortho
    ArrowThickness 3
    ArrowColor #FFFFFF
}

title 3D Shape Assignment - Class UML Diagram


interface 2D_Shape {
    --[Methods]--
    + float getArea()
    + String areaExplain()
}

interface 3D_Shape {
    --[Methods]--
    + float getVolume()
    + float getSurfaceArea()
    + String volumeExplain()
    + String surfaceAreaExplain()
}

class Circle implements 2D_Shape {
    - float radius
    --[Contructor]--
    + Circle(float)
    --[Methods]--
    + float getArea()
    + float getRadius()
    + float getCircumference()
    + String areaExplain()

}

class Cuboid extends Prism {
    --[Constructor]--
    + Cuboid(float, float, float)
    --[Methods]--
    - Rectangle getBase()
    # Rectangle getRectangularFace()
    + float getVolume()
    + float getSurfaceArea()
    + String surfaceAreaExplain()
    + String volumeExplain()
}

class Cylinder extends Prism {
    --[Constructor]--
    + Cylinder(float, float)
    --[Methods]--
    - Circle getBase()
    # Rectangle getRectangularFace()
    + float getVolume()
    + float getSurfaceArea()
    + String surfaceAreaExplain()
    + String volumeExplain()
}

class Equilateral_Triangle extends Triangle {
    - float side
    --[Constructor]--
    + Equilateral_Triangle(float)
    --[Methods]--
    + float getSide()
    + float getArea()
    + String areaExplain()
}

abstract class Prism implements 3D_Shape {
    # 2D_Shape base
    # float height
    --[Methods]--
    # {abstract} Rectangle getRectangularFace()
}

abstract class Pyramid implements 3D_Shape {
    # 2D_Shape base
    # float height
}

class Rectangle implements 2D_Shape {
    - float width
    - float length
    --[Constructor]--
    + Rectangle(float, float)
    --[Methods]--
    + float getWidth()
    + float getLength()
    + float getArea()
    + String areaExplain()
}

class Sphere implements 3D_Shape {
    - float radius
    --[Constructor]--
    + Sphere(float)
    --[Methods]--
    + float getVolume()
    + float getSurfaceArea()
    + String surfaceAreaExplain()
    + String volumeExplain()
}

class Square implements 2D_Shape {
    - float side
    --[Constructor]--
    + Square(float)
    --[Methods]--
    + float getSide()
    + float getArea()
    + String areaExplain()
}

class Square_Pyramid extends Pyramid {
    --[Constructor]--
    + Square_Pyramid(float, float)
    --[Methods]--
    + float getVolume()
    + float getSurfaceArea()
    + String volumeExplain()
    + String surfaceAreaExplain()
}

class Triangle implements 2D_Shape {

}

class TriPrism extends Prism    {

}

class TriPyramid extends Pyramid {
    --[Constructor]--
    + TriPyramid(float, float)
    --[Methods]--
    + float getVolume()
    + float getSurfaceArea()
    + String volumeExplain()
    + String surfaceAreaExplain()
}

@enduml